import json
import os
import re
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from string import Template
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

CONFIG_DIR_NAME = ".ov_mgn"
SERVER_CONFIG_NAME = "server.json"
SERVER_LOCK_NAME = "server.json.lock"
RELEASE_LOCK_NAME = "release.json.lock"
STATE_NAME = "state.json"
DEFAULT_CONFIG_TEMPLATE = """# Generated by ov-mgn.
profile = "${profile}"
service = "${service}"
release_id = "${release_id}"
"""
SERVICE_NAME_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
ENV_KEY_PATTERN = re.compile(r"^[A-Z_][A-Z0-9_]*$")


class SourceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = Field(default=None)
    ref: str | None = Field(default=None)
    path: Path | None = Field(default=None)

    @model_validator(mode="after")
    def validate_source(self) -> "SourceSpec":
        if self.type == "git" and not (self.repo and self.repo.strip()):
            raise ValueError("git source requires repo")
        if self.type == "local" and not self.path:
            raise ValueError("local source requires path")
        if self.type == "local" and self.path:
            source_path = self.path.expanduser()
            if not source_path.exists() or not source_path.is_dir():
                raise ValueError("local source path must exist and be a directory")
        return self


class OpenVikingSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str] = Field(default_factory=dict)
    env: dict[str, str] = Field(default_factory=dict)
    template_path: Path | None = Field(default=None)

    @field_validator("vars")
    @classmethod
    def validate_vars(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not key:
                raise ValueError("vars keys must be non-empty strings")
        return value

    @field_validator("env")
    @classmethod
    def validate_env(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not ENV_KEY_PATTERN.fullmatch(key):
                raise ValueError("env keys must match [A-Z_][A-Z0-9_]*")
        return value

    @field_validator("template_path")
    @classmethod
    def validate_template_path(cls, value: Path | None) -> Path | None:
        if value is None:
            return value
        template_path = value.expanduser()
        if not template_path.exists() or not template_path.is_file():
            raise ValueError("template_path must exist and be a file")
        return value


class ServerDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    port_range: tuple[int, int] = Field(default=(30000, 39999))
    image: str = Field(default="openviking/openviking:latest")
    data_root: Path = Field(default=Path("~/.ov_mgn/data"))
    secret_env_file: Path | None = Field(default=Path("~/.ov_mgn/secrets.env"))

    @field_validator("port_range")
    @classmethod
    def validate_port_range(cls, value: tuple[int, int]) -> tuple[int, int]:
        start, end = value
        if start < 1 or end > 65535 or start > end:
            raise ValueError("port_range must be within 1..65535 and start <= end")
        return value


class ServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(default=True)
    stable_host: str = Field(default="127.0.0.1")
    stable_port: int = Field(ge=1, le=65535)
    image: str | None = Field(default=None)
    source: SourceSpec
    openviking: OpenVikingSpec = Field(default_factory=OpenVikingSpec)


class UserServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = Field(default=1)
    defaults: ServerDefaults = Field(default_factory=ServerDefaults)
    services: dict[str, ServiceSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_services(self) -> "UserServerConfig":
        stable_ports: dict[int, str] = {}
        range_start, range_end = self.defaults.port_range
        for name, service in self.services.items():
            if not SERVICE_NAME_PATTERN.fullmatch(name):
                raise ValueError(f"invalid service name: {name}")
            if service.stable_port in stable_ports:
                other = stable_ports[service.stable_port]
                raise ValueError(
                    f"stable_port {service.stable_port} is used by both {other} and {name}"
                )
            stable_ports[service.stable_port] = name
            if range_start <= service.stable_port <= range_end:
                raise ValueError(
                    f"port_range {range_start}-{range_end} must not include stable_port "
                    f"{service.stable_port} for {name}"
                )
        return self


class LockedSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = None
    ref: str | None = None
    commit_sha: str | None = None
    original_path: Path | None = None
    snapshot_path: Path | None = None


class LockedOpenViking(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str]
    env: dict[str, str]
    template_path: Path | None
    config_file: Path


class LockedServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool
    image: str
    stable_host: str
    stable_port: int
    candidate_host: str
    candidate_port: int
    release_id: str
    source: LockedSource
    network_name: str
    candidate_container_name: str
    online_container_name: str
    code_dir: Path
    config_dir: Path
    candidate_data_dir: Path
    release_data_dir: Path
    secret_env_file: Path | None
    openviking: LockedOpenViking


class LockedServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int
    generated_at: datetime
    source: Path
    services: dict[str, LockedServiceSpec]


class ReleaseLock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, LockedServiceSpec] = Field(default_factory=dict)


class RuntimeServiceState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    candidate_release_id: str | None = None
    online_release_id: str | None = None
    stable_host: str | None = None
    stable_port: int | None = None


class RuntimeState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, RuntimeServiceState] = Field(default_factory=dict)


def get_config_dir(home: Path | None = None) -> Path:
    return (home or Path.home()) / CONFIG_DIR_NAME


def get_server_config_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_CONFIG_NAME


def get_server_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_LOCK_NAME


def get_release_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / RELEASE_LOCK_NAME


def get_state_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / STATE_NAME


def load_user_server_config(path: Path | None = None) -> UserServerConfig:
    config_path = path or get_server_config_path()
    if not config_path.exists():
        return UserServerConfig()

    with config_path.open("r", encoding="utf-8") as file:
        return UserServerConfig.model_validate(json.load(file))


def save_user_server_config(config: UserServerConfig, path: Path | None = None) -> Path:
    config_path = path or get_server_config_path()
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    return _write_user_json_atomic(validated, config_path)


def save_user_server_config_data(data: dict[str, Any], path: Path | None = None) -> Path:
    UserServerConfig.model_validate(data)
    return _write_user_json_data_atomic(data, path or get_server_config_path())


def update_user_server_config(
    updater: Callable[[UserServerConfig], None],
    path: Path | None = None,
) -> UserServerConfig:
    config = load_user_server_config(path)
    updater(config)
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    save_user_server_config(validated, path)
    return validated


def load_locked_config(path: Path | None = None) -> LockedServerConfig:
    with (path or get_server_lock_path()).open("r", encoding="utf-8") as file:
        return LockedServerConfig.model_validate(json.load(file))


def load_release_lock(path: Path | None = None) -> ReleaseLock:
    release_path = path or get_release_lock_path()
    if not release_path.exists():
        return ReleaseLock(updated_at=datetime.now(UTC))
    with release_path.open("r", encoding="utf-8") as file:
        return ReleaseLock.model_validate(json.load(file))


def load_state(path: Path | None = None) -> RuntimeState:
    state_path = path or get_state_path()
    if not state_path.exists():
        return RuntimeState(updated_at=datetime.now(UTC))
    with state_path.open("r", encoding="utf-8") as file:
        return RuntimeState.model_validate(json.load(file))


def render_locked_config(
    config: UserServerConfig,
    source: Path | None = None,
    generated_at: datetime | None = None,
    used_ports: set[int] | None = None,
) -> LockedServerConfig:
    generated_at = generated_at or datetime.now(UTC)
    source = source or get_server_config_path()
    allocated_ports = set(used_ports or set())
    allocated_ports.update(service.stable_port for service in config.services.values())
    services: dict[str, LockedServiceSpec] = {}

    for name, spec in sorted(config.services.items()):
        service = _render_locked_service(name, config.defaults, spec, generated_at, allocated_ports)
        services[name] = service
        allocated_ports.add(service.candidate_port)

    return LockedServerConfig(
        version=config.version,
        generated_at=generated_at,
        source=source,
        services=services,
    )


def write_lock_file(config: LockedServerConfig, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_server_lock_path())


def write_release_lock(config: ReleaseLock, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_release_lock_path())


def write_state(config: RuntimeState, path: Path | None = None) -> Path:
    state_path = path or get_state_path()
    state_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    with state_path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(config), file, ensure_ascii=False, indent=2)
        file.write("\n")
    state_path.chmod(0o600)
    return state_path


def materialize_service(service: LockedServiceSpec) -> None:
    service.code_dir.mkdir(parents=True, exist_ok=True)
    service.config_dir.mkdir(parents=True, exist_ok=True)
    service.candidate_data_dir.mkdir(parents=True, exist_ok=True)

    if service.source.type == "local" and service.source.original_path:
        if service.code_dir.exists():
            shutil.rmtree(service.code_dir)
        shutil.copytree(service.source.original_path.expanduser(), service.code_dir)

    _render_openviking_config(service)


def promote_data_dir(service: LockedServiceSpec) -> None:
    service.release_data_dir.parent.mkdir(parents=True, exist_ok=True)
    if service.release_data_dir.exists():
        return
    if service.candidate_data_dir.exists():
        shutil.move(str(service.candidate_data_dir), str(service.release_data_dir))
    else:
        service.release_data_dir.mkdir(parents=True, exist_ok=True)


def _render_locked_service(
    name: str,
    defaults: ServerDefaults,
    spec: ServiceSpec,
    generated_at: datetime,
    used_ports: set[int],
) -> LockedServiceSpec:
    short_sha = _source_short_sha(spec.source)
    release_id = f"{name}-{generated_at.strftime('%Y%m%dT%H%M%S')}-{short_sha}"
    data_root = defaults.data_root.expanduser()
    release_root = data_root / name / "releases" / release_id
    candidate_port = _allocate_port(defaults.port_range, used_ports)
    source = _lock_source(spec.source, release_root / "code")
    variables = {"profile": name, "service": name, "release_id": release_id, **spec.openviking.vars}

    return LockedServiceSpec(
        enabled=spec.enabled,
        image=spec.image or defaults.image,
        stable_host=spec.stable_host,
        stable_port=spec.stable_port,
        candidate_host=spec.stable_host,
        candidate_port=candidate_port,
        release_id=release_id,
        source=source,
        network_name=f"ov-mgn-{name}",
        candidate_container_name=f"ov-mgn-{name}-candidate-{release_id}",
        online_container_name=f"ov-mgn-{name}-online",
        code_dir=release_root / "code",
        config_dir=release_root / "config",
        candidate_data_dir=data_root / name / "candidates" / release_id / "data",
        release_data_dir=release_root / "data",
        secret_env_file=defaults.secret_env_file.expanduser() if defaults.secret_env_file else None,
        openviking=LockedOpenViking(
            vars=variables,
            env=spec.openviking.env,
            template_path=spec.openviking.template_path,
            config_file=release_root / "config" / "openviking.conf",
        ),
    )


def _source_short_sha(source: SourceSpec) -> str:
    if source.type == "git":
        commit = _resolve_git_commit(source)
        return commit[:7]
    if source.path:
        return _resolve_local_sha(source.path)[:7]
    return "unknown"


def _lock_source(source: SourceSpec, code_dir: Path) -> LockedSource:
    if source.type == "git":
        return LockedSource(
            type="git",
            repo=source.repo,
            ref=source.ref,
            commit_sha=_resolve_git_commit(source),
        )
    return LockedSource(
        type="local",
        original_path=source.path.expanduser() if source.path else None,
        snapshot_path=code_dir,
    )


def _resolve_git_commit(source: SourceSpec) -> str:
    repo = source.repo or ""
    ref = source.ref or "HEAD"
    repo_path = Path(repo).expanduser()
    if repo_path.exists():
        command = ["git", "-C", str(repo_path), "rev-parse", ref]
    else:
        command = ["git", "ls-remote", repo, ref]
    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    output = result.stdout.strip()
    if not output:
        return "unknown"
    return output.split()[0]


def _resolve_local_sha(path: Path) -> str:
    repo_path = path.expanduser()
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "local"
    return result.stdout.strip() or "local"


def _allocate_port(port_range: tuple[int, int], used_ports: set[int]) -> int:
    start, end = port_range
    for port in range(start, end + 1):
        if port not in used_ports:
            return port
    raise ValueError(f"no free port in range {start}-{end}")


def _render_openviking_config(service: LockedServiceSpec) -> None:
    template_text = DEFAULT_CONFIG_TEMPLATE
    if service.openviking.template_path:
        template_text = service.openviking.template_path.expanduser().read_text(encoding="utf-8")
    rendered = Template(template_text).safe_substitute(service.openviking.vars)
    service.openviking.config_file.parent.mkdir(parents=True, exist_ok=True)
    service.openviking.config_file.write_text(rendered, encoding="utf-8")


def _write_json_read_only(model: BaseModel, path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    if path.exists():
        path.chmod(0o600)
    with path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(model), file, ensure_ascii=False, indent=2)
        file.write("\n")
    path.chmod(0o444)
    return path


def _write_user_json_atomic(model: BaseModel, path: Path) -> Path:
    return _write_user_json_data_atomic(_json_ready(model), path)


def _write_user_json_data_atomic(data: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
        text=True,
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            json.dump(data, file, ensure_ascii=False, indent=2, sort_keys=True)
            file.write("\n")
            file.flush()
            os.fsync(file.fileno())
        temp_path.chmod(0o600)
        os.replace(temp_path, path)
        path.chmod(0o600)
    except Exception:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass
        raise
    return path


def _json_ready(model: BaseModel) -> dict[str, Any]:
    return model.model_dump(mode="json")


def is_read_only(path: Path) -> bool:
    return path.exists() and path.stat().st_mode & 0o222 == 0
