import json
import os
import re
import secrets
import tempfile
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

CONFIG_DIR_NAME = ".ov_mgn"
SERVER_CONFIG_NAME = "server.json"
SERVER_LOCK_NAME = "server.json.lock"
RELEASE_LOCK_NAME = "release.json.lock"
STATE_NAME = "state.json.lock"
DEFAULT_CONFIG_TEMPLATE = """# Generated by ov-mgn.
profile = "${profile}"
service = "${service}"
release_id = "${release_id}"
"""
OPENVIKING_CONFIG_FILE = "/app/config/openviking.conf"
OPENVIKING_MANAGED_ENV_KEYS = {
    "OPENVIKING_CONFIG_FILE",
    "OPENVIKING_CLI_CONFIG_FILE",
    "VIKINGBOT_API_KEY",
    "PATH",
}
OPENVIKING_MODEL_SECTIONS = {"embedding", "vlm"}
SERVICE_NAME_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
ENV_KEY_PATTERN = re.compile(r"^[A-Z_][A-Z0-9_]*$")
ROUTE_PATH_PATTERN = re.compile(r"^/[A-Za-z0-9_/-]*/$")


class SourceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = Field(default=None)
    ref: str | None = Field(default=None)
    path: Path | None = Field(default=None)

    @model_validator(mode="after")
    def validate_source(self) -> "SourceSpec":
        if self.type == "git" and not (self.repo and self.repo.strip()):
            raise ValueError("git source requires repo")
        if self.type == "local" and not self.path:
            raise ValueError("local source requires path")
        if self.type == "local" and self.path:
            source_path = self.path.expanduser()
            if not source_path.exists() or not source_path.is_dir():
                raise ValueError("local source path must exist and be a directory")
        return self


class OpenVikingSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str] = Field(default_factory=dict)
    env: dict[str, str] = Field(default_factory=dict)
    template_path: Path | None = Field(default=None)

    @field_validator("vars")
    @classmethod
    def validate_vars(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not key:
                raise ValueError("vars keys must be non-empty strings")
        return value

    @field_validator("env")
    @classmethod
    def validate_env(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not ENV_KEY_PATTERN.fullmatch(key):
                raise ValueError("env keys must match [A-Z_][A-Z0-9_]*")
            if key in OPENVIKING_MANAGED_ENV_KEYS:
                raise ValueError(f"{key} is managed by ov-mgn and cannot be set in openviking.env")
        return value


class ServerDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    port_range: tuple[int, int] = Field(default=(30000, 39999))
    image: str = Field(default="ghcr.io/volcengine/openviking:latest")
    backend_port: int = Field(default=1933, ge=1, le=65535)
    data_root: Path = Field(default=Path("~/.ov_mgn/data"))
    secret_env_file: Path | None = Field(default=None)
    openviking: "OpenVikingDefaults" = Field(default_factory=lambda: OpenVikingDefaults())
    gateway: "GatewayDefaults" = Field(default_factory=lambda: GatewayDefaults())

    @field_validator("port_range")
    @classmethod
    def validate_port_range(cls, value: tuple[int, int]) -> tuple[int, int]:
        start, end = value
        if start < 1 or end > 65535 or start > end:
            raise ValueError("port_range must be within 1..65535 and start <= end")
        return value


class OpenVikingDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    model_config_file: Path = Field(default=Path("~/.ov_mgn/model.json"))
    root_api_key: str | None = Field(default=None)

    @field_validator("root_api_key")
    @classmethod
    def validate_root_api_key(cls, value: str | None) -> str | None:
        if value is None:
            return value
        stripped = value.strip()
        if not stripped:
            raise ValueError("root_api_key must be non-empty")
        return stripped


class BranchSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    parent_service: str
    declared_at: datetime

    @field_validator("parent_service")
    @classmethod
    def validate_parent_service(cls, value: str) -> str:
        if not SERVICE_NAME_PATTERN.fullmatch(value):
            raise ValueError("branch parent_service must be a valid service name")
        return value


class ServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(default=True)
    stable_host: str = Field(default="127.0.0.1")
    stable_port: int = Field(default=0, ge=0, le=65535)
    route_path: str | None = Field(default=None)
    image: str | None = Field(default=None)
    source: SourceSpec
    openviking: OpenVikingSpec = Field(default_factory=OpenVikingSpec)
    branch: BranchSpec | None = Field(default=None)

    @field_validator("route_path")
    @classmethod
    def validate_route_path(cls, value: str | None) -> str | None:
        if value is None:
            return value
        if not ROUTE_PATH_PATTERN.fullmatch(value):
            raise ValueError("route_path must start and end with / and contain path-safe chars")
        if "/__candidate/" in value:
            raise ValueError("route_path must not include __candidate")
        if value.startswith("/__ov-mgn/"):
            raise ValueError("route_path must not use reserved /__ov-mgn/ prefix")
        return value


class GatewayDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(default=True)
    host: str = Field(default="127.0.0.1")
    port: int = Field(default=18080, ge=1, le=65535)
    image: str = Field(default="nginx:stable-alpine")
    network_name: str = Field(default="ov-mgn-gateway")

    @model_validator(mode="after")
    def validate_gateway(self) -> "GatewayDefaults":
        if not self.enabled:
            raise ValueError(
                "only gateway mode is supported; defaults.gateway.enabled must be true"
            )
        return self


class UserServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = Field(default=1)
    defaults: ServerDefaults = Field(default_factory=ServerDefaults)
    services: dict[str, ServiceSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_services(self) -> "UserServerConfig":
        route_paths: dict[str, str] = {}
        for name, service in self.services.items():
            if not SERVICE_NAME_PATTERN.fullmatch(name):
                raise ValueError(f"invalid service name: {name}")
            route_path = service.route_path or f"/{name}/"
            if route_path.startswith("/__ov-mgn/"):
                raise ValueError("route_path must not use reserved /__ov-mgn/ prefix")
            if route_path in route_paths:
                other = route_paths[route_path]
                raise ValueError(f"route_path {route_path} is used by both {other} and {name}")
            if service.branch:
                if service.branch.parent_service == name:
                    raise ValueError(f"service {name} cannot branch from itself")
                if service.branch.parent_service not in self.services:
                    raise ValueError(
                        f"branch parent_service {service.branch.parent_service} "
                        f"for {name} is not present in services"
                    )
            route_paths[route_path] = name
        return self


class LockedSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = None
    ref: str | None = None
    commit_sha: str | None = None
    original_path: Path | None = None
    snapshot_path: Path | None = None


class LockedOpenViking(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str]
    env: dict[str, str]
    template_path: Path | None
    model_config_file: Path = Field(default=Path("~/.ov_mgn/model.json"))
    config_file: Path
    cli_config_file: Path | None = None


class LockedServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool
    image: str
    backend_port: int = Field(default=1933, ge=1, le=65535)
    stable_host: str
    stable_port: int
    candidate_host: str
    candidate_port: int
    route_path: str
    release_id: str
    source: LockedSource
    network_name: str
    candidate_container_name: str
    online_container_name: str
    release_container_name: str
    code_dir: Path
    config_dir: Path
    candidate_data_dir: Path
    release_data_dir: Path
    secret_env_file: Path | None
    openviking: LockedOpenViking
    branch: BranchSpec | None = None


class LockedServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int
    generated_at: datetime
    source: Path
    gateway: GatewayDefaults
    gateway_config_path: Path
    gateway_container_name: str
    services: dict[str, LockedServiceSpec]


class ReleaseLock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, LockedServiceSpec] = Field(default_factory=dict)


class RuntimeServiceState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    candidate_release_id: str | None = None
    online_release_id: str | None = None
    stable_host: str | None = None
    stable_port: int | None = None


class RuntimeState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, RuntimeServiceState] = Field(default_factory=dict)


def get_config_dir(home: Path | None = None) -> Path:
    return (home or Path.home()) / CONFIG_DIR_NAME


def get_server_config_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_CONFIG_NAME


def get_server_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_LOCK_NAME


def get_release_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / RELEASE_LOCK_NAME


def get_state_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / STATE_NAME


def load_user_server_config(path: Path | None = None) -> UserServerConfig:
    config_path = path or get_server_config_path()
    if not config_path.exists():
        return UserServerConfig()

    with config_path.open("r", encoding="utf-8") as file:
        return UserServerConfig.model_validate(json.load(file))


def save_user_server_config(config: UserServerConfig, path: Path | None = None) -> Path:
    config_path = path or get_server_config_path()
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    return _write_user_json_atomic(validated, config_path)


def ensure_user_server_root_api_key(
    config: UserServerConfig,
    path: Path | None = None,
) -> UserServerConfig:
    if config.defaults.openviking.root_api_key:
        return config
    openviking = config.defaults.openviking.model_copy(
        update={"root_api_key": secrets.token_urlsafe(32)}
    )
    defaults = config.defaults.model_copy(update={"openviking": openviking})
    updated = UserServerConfig.model_validate(config.model_copy(update={"defaults": defaults}))
    save_user_server_config(updated, path)
    return updated


def save_user_server_config_data(data: dict[str, Any], path: Path | None = None) -> Path:
    UserServerConfig.model_validate(data)
    return _write_user_json_data_atomic(data, path or get_server_config_path())


def update_user_server_config(
    updater: Callable[[UserServerConfig], None],
    path: Path | None = None,
) -> UserServerConfig:
    config = load_user_server_config(path)
    updater(config)
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    save_user_server_config(validated, path)
    return validated


def load_locked_config(path: Path | None = None) -> LockedServerConfig:
    with (path or get_server_lock_path()).open("r", encoding="utf-8") as file:
        return LockedServerConfig.model_validate(json.load(file))


def load_release_lock(path: Path | None = None) -> ReleaseLock:
    release_path = path or get_release_lock_path()
    if not release_path.exists():
        return ReleaseLock(updated_at=datetime.now(UTC))
    with release_path.open("r", encoding="utf-8") as file:
        return ReleaseLock.model_validate(json.load(file))


def load_state(path: Path | None = None) -> RuntimeState:
    state_path = path or get_state_path()
    if not state_path.exists():
        return RuntimeState(updated_at=datetime.now(UTC))
    with state_path.open("r", encoding="utf-8") as file:
        return RuntimeState.model_validate(json.load(file))


def render_locked_config(
    config: UserServerConfig,
    source: Path | None = None,
    generated_at: datetime | None = None,
    used_ports: set[int] | None = None,
) -> LockedServerConfig:
    from ov_mgn.server_render import render_locked_config as _render_locked_config

    return _render_locked_config(
        config,
        source=source,
        generated_at=generated_at,
        used_ports=used_ports,
    )


def validate_openviking_model_config(config: UserServerConfig) -> None:
    from ov_mgn.openviking import validate_openviking_model_config as _validate

    _validate(config)


def write_lock_file(config: LockedServerConfig, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_server_lock_path())


def write_release_lock(config: ReleaseLock, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_release_lock_path())


def write_state(config: RuntimeState, path: Path | None = None) -> Path:
    state_path = path or get_state_path()
    state_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    with state_path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(config), file, ensure_ascii=False, indent=2)
        file.write("\n")
    state_path.chmod(0o600)
    return state_path


def materialize_service(service: LockedServiceSpec, *, root_api_key: str | None = None) -> None:
    from ov_mgn.server_render import materialize_service as _materialize_service

    _materialize_service(service, root_api_key=root_api_key)


def configure_openviking_user(
    service: LockedServiceSpec,
    *,
    api_key: str,
    account: str = "default",
    user: str = "default",
) -> LockedServiceSpec:
    from ov_mgn.openviking import configure_openviking_user as _configure_openviking_user

    return _configure_openviking_user(service, api_key=api_key, account=account, user=user)


def promote_data_dir(service: LockedServiceSpec) -> None:
    from ov_mgn.server_render import promote_data_dir as _promote_data_dir

    _promote_data_dir(service)


def _write_json_read_only(model: BaseModel, path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    if path.exists():
        path.chmod(0o600)
    with path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(model), file, ensure_ascii=False, indent=2)
        file.write("\n")
    path.chmod(0o444)
    return path


def _write_user_json_atomic(model: BaseModel, path: Path) -> Path:
    return _write_user_json_data_atomic(_json_ready(model), path)


def _write_user_json_data_atomic(data: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
        text=True,
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            json.dump(data, file, ensure_ascii=False, indent=2, sort_keys=True)
            file.write("\n")
            file.flush()
            os.fsync(file.fileno())
        temp_path.chmod(0o600)
        os.replace(temp_path, path)
        path.chmod(0o600)
    except Exception:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass
        raise
    return path


def _json_ready(model: BaseModel) -> dict[str, Any]:
    return model.model_dump(mode="json")


def is_read_only(path: Path) -> bool:
    return path.exists() and path.stat().st_mode & 0o222 == 0
