import json
import os
import re
import secrets
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

CONFIG_DIR_NAME = ".ov_mgn"
SERVER_CONFIG_NAME = "server.json"
SERVER_LOCK_NAME = "server.json.lock"
RELEASE_LOCK_NAME = "release.json.lock"
STATE_NAME = "state.json.lock"
DEFAULT_CONFIG_TEMPLATE = """# Generated by ov-mgn.
profile = "${profile}"
service = "${service}"
release_id = "${release_id}"
"""
OPENVIKING_CONFIG_FILE = "/app/config/openviking.conf"
OPENVIKING_MANAGED_ENV_KEYS = {
    "OPENVIKING_CONFIG_FILE",
    "OPENVIKING_CLI_CONFIG_FILE",
    "VIKINGBOT_API_KEY",
    "PATH",
}
OPENVIKING_MODEL_SECTIONS = {"embedding", "vlm", "bot"}
SERVICE_NAME_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
ENV_KEY_PATTERN = re.compile(r"^[A-Z_][A-Z0-9_]*$")
ROUTE_PATH_PATTERN = re.compile(r"^/[A-Za-z0-9_/-]*/$")


class SourceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = Field(default=None)
    ref: str | None = Field(default=None)
    path: Path | None = Field(default=None)

    @model_validator(mode="after")
    def validate_source(self) -> "SourceSpec":
        if self.type == "git" and not (self.repo and self.repo.strip()):
            raise ValueError("git source requires repo")
        if self.type == "local" and not self.path:
            raise ValueError("local source requires path")
        if self.type == "local" and self.path:
            source_path = self.path.expanduser()
            if not source_path.exists() or not source_path.is_dir():
                raise ValueError("local source path must exist and be a directory")
        return self


class OpenVikingSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str] = Field(default_factory=dict)
    env: dict[str, str] = Field(default_factory=dict)
    template_path: Path | None = Field(default=None)

    @field_validator("vars")
    @classmethod
    def validate_vars(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not key:
                raise ValueError("vars keys must be non-empty strings")
        return value

    @field_validator("env")
    @classmethod
    def validate_env(cls, value: dict[str, str]) -> dict[str, str]:
        for key in value:
            if not isinstance(key, str) or not ENV_KEY_PATTERN.fullmatch(key):
                raise ValueError("env keys must match [A-Z_][A-Z0-9_]*")
            if key in OPENVIKING_MANAGED_ENV_KEYS:
                raise ValueError(f"{key} is managed by ov-mgn and cannot be set in openviking.env")
        return value


class ServerDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    port_range: tuple[int, int] = Field(default=(30000, 39999))
    image: str = Field(default="ghcr.io/volcengine/openviking:latest")
    backend_port: int = Field(default=1933, ge=1, le=65535)
    data_root: Path = Field(default=Path("~/.ov_mgn/data"))
    secret_env_file: Path | None = Field(default=None)
    openviking: "OpenVikingDefaults" = Field(default_factory=lambda: OpenVikingDefaults())
    gateway: "GatewayDefaults" = Field(default_factory=lambda: GatewayDefaults())

    @field_validator("port_range")
    @classmethod
    def validate_port_range(cls, value: tuple[int, int]) -> tuple[int, int]:
        start, end = value
        if start < 1 or end > 65535 or start > end:
            raise ValueError("port_range must be within 1..65535 and start <= end")
        return value


class OpenVikingDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    model_config_file: Path = Field(default=Path("~/.ov_mgn/model.json"))


class BranchSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    parent_service: str
    declared_at: datetime

    @field_validator("parent_service")
    @classmethod
    def validate_parent_service(cls, value: str) -> str:
        if not SERVICE_NAME_PATTERN.fullmatch(value):
            raise ValueError("branch parent_service must be a valid service name")
        return value


class ServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(default=True)
    stable_host: str = Field(default="127.0.0.1")
    stable_port: int = Field(default=0, ge=0, le=65535)
    route_path: str | None = Field(default=None)
    image: str | None = Field(default=None)
    source: SourceSpec
    openviking: OpenVikingSpec = Field(default_factory=OpenVikingSpec)
    branch: BranchSpec | None = Field(default=None)

    @field_validator("route_path")
    @classmethod
    def validate_route_path(cls, value: str | None) -> str | None:
        if value is None:
            return value
        if not ROUTE_PATH_PATTERN.fullmatch(value):
            raise ValueError("route_path must start and end with / and contain path-safe chars")
        if "/__candidate/" in value:
            raise ValueError("route_path must not include __candidate")
        if value.startswith("/__ov-mgn/"):
            raise ValueError("route_path must not use reserved /__ov-mgn/ prefix")
        return value


class GatewayDefaults(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool = Field(default=True)
    host: str = Field(default="127.0.0.1")
    port: int = Field(default=18080, ge=1, le=65535)
    image: str = Field(default="nginx:stable-alpine")
    network_name: str = Field(default="ov-mgn-gateway")

    @model_validator(mode="after")
    def validate_gateway(self) -> "GatewayDefaults":
        if not self.enabled:
            raise ValueError(
                "only gateway mode is supported; defaults.gateway.enabled must be true"
            )
        return self


class UserServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = Field(default=1)
    defaults: ServerDefaults = Field(default_factory=ServerDefaults)
    services: dict[str, ServiceSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_services(self) -> "UserServerConfig":
        route_paths: dict[str, str] = {}
        for name, service in self.services.items():
            if not SERVICE_NAME_PATTERN.fullmatch(name):
                raise ValueError(f"invalid service name: {name}")
            route_path = service.route_path or f"/{name}/"
            if route_path.startswith("/__ov-mgn/"):
                raise ValueError("route_path must not use reserved /__ov-mgn/ prefix")
            if route_path in route_paths:
                other = route_paths[route_path]
                raise ValueError(f"route_path {route_path} is used by both {other} and {name}")
            if service.branch:
                if service.branch.parent_service == name:
                    raise ValueError(f"service {name} cannot branch from itself")
                if service.branch.parent_service not in self.services:
                    raise ValueError(
                        f"branch parent_service {service.branch.parent_service} "
                        f"for {name} is not present in services"
                    )
            route_paths[route_path] = name
        return self


class LockedSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: Literal["git", "local"]
    repo: str | None = None
    ref: str | None = None
    commit_sha: str | None = None
    original_path: Path | None = None
    snapshot_path: Path | None = None


class LockedOpenViking(BaseModel):
    model_config = ConfigDict(extra="forbid")

    vars: dict[str, str]
    env: dict[str, str]
    template_path: Path | None
    model_config_file: Path = Field(default=Path("~/.ov_mgn/model.json"))
    config_file: Path
    cli_config_file: Path | None = None


class LockedServiceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enabled: bool
    image: str
    backend_port: int = Field(default=1933, ge=1, le=65535)
    stable_host: str
    stable_port: int
    candidate_host: str
    candidate_port: int
    route_path: str
    release_id: str
    source: LockedSource
    network_name: str
    candidate_container_name: str
    online_container_name: str
    release_container_name: str
    code_dir: Path
    config_dir: Path
    candidate_data_dir: Path
    release_data_dir: Path
    secret_env_file: Path | None
    openviking: LockedOpenViking
    branch: BranchSpec | None = None


class LockedServerConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int
    generated_at: datetime
    source: Path
    gateway: GatewayDefaults
    gateway_config_path: Path
    gateway_container_name: str
    services: dict[str, LockedServiceSpec]


class ReleaseLock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, LockedServiceSpec] = Field(default_factory=dict)


class RuntimeServiceState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    candidate_release_id: str | None = None
    online_release_id: str | None = None
    stable_host: str | None = None
    stable_port: int | None = None


class RuntimeState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = 1
    updated_at: datetime
    services: dict[str, RuntimeServiceState] = Field(default_factory=dict)


def get_config_dir(home: Path | None = None) -> Path:
    return (home or Path.home()) / CONFIG_DIR_NAME


def get_server_config_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_CONFIG_NAME


def get_server_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / SERVER_LOCK_NAME


def get_release_lock_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / RELEASE_LOCK_NAME


def get_state_path(home: Path | None = None) -> Path:
    return get_config_dir(home) / STATE_NAME


def load_user_server_config(path: Path | None = None) -> UserServerConfig:
    config_path = path or get_server_config_path()
    if not config_path.exists():
        return UserServerConfig()

    with config_path.open("r", encoding="utf-8") as file:
        return UserServerConfig.model_validate(json.load(file))


def save_user_server_config(config: UserServerConfig, path: Path | None = None) -> Path:
    config_path = path or get_server_config_path()
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    return _write_user_json_atomic(validated, config_path)


def save_user_server_config_data(data: dict[str, Any], path: Path | None = None) -> Path:
    UserServerConfig.model_validate(data)
    return _write_user_json_data_atomic(data, path or get_server_config_path())


def update_user_server_config(
    updater: Callable[[UserServerConfig], None],
    path: Path | None = None,
) -> UserServerConfig:
    config = load_user_server_config(path)
    updater(config)
    validated = UserServerConfig.model_validate(config.model_dump(mode="python"))
    save_user_server_config(validated, path)
    return validated


def load_locked_config(path: Path | None = None) -> LockedServerConfig:
    with (path or get_server_lock_path()).open("r", encoding="utf-8") as file:
        return LockedServerConfig.model_validate(json.load(file))


def load_release_lock(path: Path | None = None) -> ReleaseLock:
    release_path = path or get_release_lock_path()
    if not release_path.exists():
        return ReleaseLock(updated_at=datetime.now(UTC))
    with release_path.open("r", encoding="utf-8") as file:
        return ReleaseLock.model_validate(json.load(file))


def load_state(path: Path | None = None) -> RuntimeState:
    state_path = path or get_state_path()
    if not state_path.exists():
        return RuntimeState(updated_at=datetime.now(UTC))
    with state_path.open("r", encoding="utf-8") as file:
        return RuntimeState.model_validate(json.load(file))


def render_locked_config(
    config: UserServerConfig,
    source: Path | None = None,
    generated_at: datetime | None = None,
    used_ports: set[int] | None = None,
) -> LockedServerConfig:
    generated_at = generated_at or datetime.now(UTC)
    source = source or get_server_config_path()
    allocated_ports = set(used_ports or set())
    services: dict[str, LockedServiceSpec] = {}

    for name, spec in sorted(config.services.items()):
        service = _render_locked_service(name, config.defaults, spec, generated_at, allocated_ports)
        services[name] = service
        allocated_ports.add(service.candidate_port)

    return LockedServerConfig(
        version=config.version,
        generated_at=generated_at,
        source=source,
        gateway=config.defaults.gateway,
        gateway_config_path=config.defaults.data_root.expanduser() / "gateway" / "nginx.conf",
        gateway_container_name="ov-mgn-gateway",
        services=services,
    )


def validate_openviking_model_config(config: UserServerConfig) -> None:
    if not config.services:
        return
    deprecated = [
        name
        for name, service in sorted(config.services.items())
        if service.openviking.template_path is not None
    ]
    if deprecated:
        services = ", ".join(deprecated)
        raise ValueError(
            "services."
            f"{services}.openviking.template_path is deprecated; remove it and use "
            "defaults.openviking.model_config_file"
        )
    _load_model_config(config.defaults.openviking.model_config_file)


def write_lock_file(config: LockedServerConfig, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_server_lock_path())


def write_release_lock(config: ReleaseLock, path: Path | None = None) -> Path:
    return _write_json_read_only(config, path or get_release_lock_path())


def write_state(config: RuntimeState, path: Path | None = None) -> Path:
    state_path = path or get_state_path()
    state_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    with state_path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(config), file, ensure_ascii=False, indent=2)
        file.write("\n")
    state_path.chmod(0o600)
    return state_path


def materialize_service(service: LockedServiceSpec) -> None:
    service.code_dir.mkdir(parents=True, exist_ok=True)
    service.config_dir.mkdir(parents=True, exist_ok=True)
    service.candidate_data_dir.mkdir(parents=True, exist_ok=True)

    if service.source.type == "local" and service.source.original_path:
        if service.code_dir.exists():
            shutil.rmtree(service.code_dir)
        shutil.copytree(service.source.original_path.expanduser(), service.code_dir)

    _render_managed_openviking_config(service)
    _render_openviking_cli_wrapper(service)


def configure_openviking_user(
    service: LockedServiceSpec,
    *,
    api_key: str,
    account: str = "default",
    user: str = "default",
) -> LockedServiceSpec:
    cli_config_file = (
        service.openviking.cli_config_file or service.openviking.config_file.with_name("ovcli.conf")
    )
    cli_config = {
        "url": f"http://127.0.0.1:{service.backend_port}",
        "api_key": api_key,
        "account": account,
        "user": user,
    }
    cli_config_file.parent.mkdir(parents=True, exist_ok=True)
    cli_config_file.write_text(
        json.dumps(cli_config, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    cli_config_file.chmod(0o600)

    runtime_env_file = service.config_dir / "runtime.env"
    runtime_env_text = _merged_runtime_env(
        service.secret_env_file,
        {
            "VIKINGBOT_ENDPOINT": f"http://127.0.0.1:{service.backend_port}/bot/v1",
        },
    )
    runtime_env_file.write_text(runtime_env_text, encoding="utf-8")
    runtime_env_file.chmod(0o600)
    return service.model_copy(update={"secret_env_file": runtime_env_file})


def promote_data_dir(service: LockedServiceSpec) -> None:
    service.release_data_dir.parent.mkdir(parents=True, exist_ok=True)
    if service.release_data_dir.exists():
        return
    if service.candidate_data_dir.exists():
        shutil.move(str(service.candidate_data_dir), str(service.release_data_dir))
    else:
        service.release_data_dir.mkdir(parents=True, exist_ok=True)


def _render_locked_service(
    name: str,
    defaults: ServerDefaults,
    spec: ServiceSpec,
    generated_at: datetime,
    used_ports: set[int],
) -> LockedServiceSpec:
    short_sha = _source_short_sha(spec.source)
    release_id = f"{name}-{generated_at.strftime('%Y%m%dT%H%M%S')}-{short_sha}"
    data_root = defaults.data_root.expanduser()
    release_root = data_root / name / "releases" / release_id
    candidate_port = _allocate_port(defaults.port_range, used_ports)
    source = _lock_source(spec.source, release_root / "code")
    variables = {"profile": name, "service": name, "release_id": release_id, **spec.openviking.vars}

    return LockedServiceSpec(
        enabled=spec.enabled,
        image=spec.image or defaults.image,
        backend_port=defaults.backend_port,
        stable_host=spec.stable_host,
        stable_port=spec.stable_port,
        candidate_host=spec.stable_host,
        candidate_port=candidate_port,
        route_path=spec.route_path or f"/{name}/",
        release_id=release_id,
        source=source,
        network_name=defaults.gateway.network_name,
        candidate_container_name=f"ov-mgn-{name}-candidate-{release_id}",
        online_container_name=f"ov-mgn-{name}-online",
        release_container_name=f"ov-mgn-{name}-{release_id}",
        code_dir=release_root / "code",
        config_dir=release_root / "config",
        candidate_data_dir=data_root / name / "candidates" / release_id / "data",
        release_data_dir=release_root / "data",
        secret_env_file=defaults.secret_env_file.expanduser() if defaults.secret_env_file else None,
        openviking=LockedOpenViking(
            vars=variables,
            env=spec.openviking.env,
            template_path=spec.openviking.template_path,
            model_config_file=defaults.openviking.model_config_file.expanduser(),
            config_file=release_root / "config" / "openviking.conf",
            cli_config_file=release_root / "config" / "ovcli.conf",
        ),
        branch=spec.branch,
    )


def _source_short_sha(source: SourceSpec) -> str:
    if source.type == "git":
        commit = _resolve_git_commit(source)
        return commit[:7]
    if source.path:
        return _resolve_local_sha(source.path)[:7]
    return "unknown"


def _lock_source(source: SourceSpec, code_dir: Path) -> LockedSource:
    if source.type == "git":
        return LockedSource(
            type="git",
            repo=source.repo,
            ref=source.ref,
            commit_sha=_resolve_git_commit(source),
        )
    return LockedSource(
        type="local",
        original_path=source.path.expanduser() if source.path else None,
        snapshot_path=code_dir,
    )


def _resolve_git_commit(source: SourceSpec) -> str:
    repo = source.repo or ""
    ref = source.ref or "HEAD"
    repo_path = Path(repo).expanduser()
    if repo_path.exists():
        command = ["git", "-C", str(repo_path), "rev-parse", ref]
    else:
        command = ["git", "ls-remote", repo, ref]
    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    output = result.stdout.strip()
    if not output:
        return "unknown"
    return output.split()[0]


def _resolve_local_sha(path: Path) -> str:
    repo_path = path.expanduser()
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "local"
    return result.stdout.strip() or "local"


def _allocate_port(port_range: tuple[int, int], used_ports: set[int]) -> int:
    start, end = port_range
    for port in range(start, end + 1):
        if port not in used_ports:
            return port
    raise ValueError(f"no free port in range {start}-{end}")


def _render_managed_openviking_config(service: LockedServiceSpec) -> None:
    if service.openviking.template_path is not None:
        raise ValueError(
            "openviking.template_path is deprecated; remove it and use "
            "defaults.openviking.model_config_file"
        )
    root_api_key = _existing_root_api_key(service.openviking.config_file) or secrets.token_urlsafe(
        32
    )
    model_config = _load_model_config(service.openviking.model_config_file)
    config: dict[str, Any] = {
        "server": {
            "host": "0.0.0.0",
            "port": service.backend_port,
            "root_api_key": root_api_key,
        },
        "storage": {
            "workspace": "/app/data",
            "vectordb": {"provider": "local"},
            "agfs": {"provider": "local"},
        },
        "runtime": {
            "managed_by": "ov-mgn",
            "service": service.openviking.vars.get("service"),
            "profile": service.openviking.vars.get("profile"),
            "release_id": service.release_id,
        },
    }
    config.update(model_config)
    rendered = json.dumps(config, ensure_ascii=False, indent=2) + "\n"
    service.openviking.config_file.parent.mkdir(parents=True, exist_ok=True)
    service.openviking.config_file.write_text(rendered, encoding="utf-8")
    _render_openviking_cli_config(service, rendered)


def _load_model_config(path: Path) -> dict[str, Any]:
    model_config_path = path.expanduser()
    if not model_config_path.exists() or not model_config_path.is_file():
        raise ValueError(f"model_config_file must exist and be a file: {model_config_path}")
    try:
        payload = json.loads(model_config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"model_config_file must be valid JSON: {model_config_path}") from exc
    if not isinstance(payload, dict):
        raise ValueError("model_config_file must contain a JSON object")
    unknown = sorted(set(payload) - OPENVIKING_MODEL_SECTIONS)
    if unknown:
        raise ValueError(
            "model_config_file may only contain top-level sections: "
            f"{', '.join(sorted(OPENVIKING_MODEL_SECTIONS))}; found {', '.join(unknown)}"
        )
    if not any(section in payload for section in OPENVIKING_MODEL_SECTIONS):
        raise ValueError("model_config_file must contain at least one of embedding, vlm, bot")
    return payload


def _existing_root_api_key(path: Path) -> str | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    root_api_key = (
        payload.get("server", {}).get("root_api_key") if isinstance(payload, dict) else None
    )
    return root_api_key if isinstance(root_api_key, str) and root_api_key else None


def _render_openviking_cli_config(service: LockedServiceSpec, openviking_config: str) -> None:
    try:
        parsed = json.loads(openviking_config)
    except json.JSONDecodeError:
        return
    root_api_key = parsed.get("server", {}).get("root_api_key")
    if not root_api_key:
        return
    cli_config = {
        "url": f"http://127.0.0.1:{service.backend_port}",
        "api_key": root_api_key,
        "account": "default",
        "user": "default",
    }
    cli_config_file = (
        service.openviking.cli_config_file or service.openviking.config_file.with_name("ovcli.conf")
    )
    cli_config_file.write_text(
        json.dumps(cli_config, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _render_openviking_cli_wrapper(service: LockedServiceSpec) -> None:
    wrapper_dir = service.config_dir / "bin"
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    wrapper = wrapper_dir / "ov"
    wrapper.write_text(
        f"""#!/bin/sh
set -eu
if [ "${{1:-}}" = "admin" ]; then
  exec /app/.venv/bin/ov "$@"
fi

root_config="/tmp/ov-mgn-root-ovcli.conf"
user_config="/tmp/ov-mgn-user-ovcli.conf"
python - <<'PY' "$root_config" 2>/dev/null || true
import json
import sys
try:
    config = json.load(open('/app/config/openviking.conf'))
    json.dump(
        {{
            'url': 'http://127.0.0.1:{service.backend_port}',
            'api_key': config['server']['root_api_key'],
            'account': 'default',
            'user': 'default',
        }},
        open(sys.argv[1], 'w'),
    )
except Exception:
    pass
PY

api_key=""
if [ -s "$root_config" ]; then
  bootstrap_json="$(OPENVIKING_CLI_CONFIG_FILE="$root_config" \\
    /app/.venv/bin/ov admin regenerate-key default default -o json 2>/dev/null || true)"
  api_key="$(BOOTSTRAP_JSON="$bootstrap_json" python - <<'PY' 2>/dev/null || true
import json
import os
try:
    payload = json.loads(os.environ.get('BOOTSTRAP_JSON', ''))
    print(payload.get('result', {{}}).get('user_key', ''))
except Exception:
    pass
PY
)"
fi

if [ -n "$api_key" ]; then
  python - <<'PY' "$user_config" "$api_key" 2>/dev/null || true
import json
import sys
json.dump(
    {{
        'url': 'http://127.0.0.1:{service.backend_port}',
        'api_key': sys.argv[2],
        'account': 'default',
        'user': 'default',
    }},
    open(sys.argv[1], 'w'),
)
PY
  export OPENVIKING_CLI_CONFIG_FILE="$user_config"
  export VIKINGBOT_API_KEY="$api_key"
fi
export VIKINGBOT_ENDPOINT="${{VIKINGBOT_ENDPOINT:-http://127.0.0.1:{service.backend_port}/bot/v1}}"
exec /app/.venv/bin/ov "$@"
""",
        encoding="utf-8",
    )
    wrapper.chmod(0o755)


def _merged_runtime_env(secret_env_file: Path | None, values: dict[str, str]) -> str:
    lines: list[str] = []
    if secret_env_file:
        secret_path = secret_env_file.expanduser()
        if secret_path.exists():
            lines.extend(
                line
                for line in secret_path.read_text(encoding="utf-8").splitlines()
                if _env_line_key(line) not in OPENVIKING_MANAGED_ENV_KEYS
            )
            lines.append("")
    lines.extend(f"{key}={value}" for key, value in sorted(values.items()))
    return "\n".join(lines).rstrip() + "\n"


def _env_line_key(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or "=" not in stripped:
        return None
    return stripped.split("=", 1)[0].strip()


def _write_json_read_only(model: BaseModel, path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    if path.exists():
        path.chmod(0o600)
    with path.open("w", encoding="utf-8") as file:
        json.dump(_json_ready(model), file, ensure_ascii=False, indent=2)
        file.write("\n")
    path.chmod(0o444)
    return path


def _write_user_json_atomic(model: BaseModel, path: Path) -> Path:
    return _write_user_json_data_atomic(_json_ready(model), path)


def _write_user_json_data_atomic(data: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
        text=True,
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            json.dump(data, file, ensure_ascii=False, indent=2, sort_keys=True)
            file.write("\n")
            file.flush()
            os.fsync(file.fileno())
        temp_path.chmod(0o600)
        os.replace(temp_path, path)
        path.chmod(0o600)
    except Exception:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass
        raise
    return path


def _json_ready(model: BaseModel) -> dict[str, Any]:
    return model.model_dump(mode="json")


def is_read_only(path: Path) -> bool:
    return path.exists() and path.stat().st_mode & 0o222 == 0
